import {
  AcademySettings,
  Assignment,
  Book,
  ClassItem,
  Course,
  NotificationItem,
  Order,
  RecordedVideo,
  User,
} from '../types';

export const INITIAL_SETTINGS: AcademySettings = {
  name: 'آموزشگاه زبان پل',
  englishName: 'Pol Language Center',
  slogan: 'پلی به سوی آینده‌ای بهتر',
  logoUrl: '/assets/logo.png',
  phone: '021-88776655',
  email: 'info@pol-academy.ir',
  address: 'تهران، خیابان ولیعصر، نرسیده به میدان ونک، پلاک ۱۲۴',
  aboutText:
    'آموزشگاه زبان پل با بیش از ۱۵ سال سابقه درخشان در تدریس زبان انگلیسی، آیلتس، مکالمه و دوره‌های تجاری، بستری هوشمند و مدرن برای یادگیری زبان‌آموزان سراسر کشور فراهم آورده است.',
  instagram: 'pol_language_center',
  telegram: 'pol_academy',
  linkedin: 'pol-language-center',
};

export const INITIAL_USERS: User[] = [
  {
    uid: 'user_admin_1',
    firstName: 'مدیر',
    lastName: 'سیستم',
    username: 'admin',
    phone: '09120000001',
    email: 'admin@demo.com',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    createdAt: '2026-01-01T08:00:00.000Z',
  },
  {
    uid: 'user_teacher_1',
    firstName: 'دکتر محمدرضا',
    lastName: 'رضایی',
    username: 'teacher_rezaei',
    phone: '09120000002',
    email: 'teacher@demo.com',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    uid: 'user_teacher_2',
    firstName: 'سارا',
    lastName: 'احمدی',
    username: 'teacher_ahmadi',
    phone: '09120000003',
    email: 'ahmadi@demo.com',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    uid: 'user_student_1',
    firstName: 'حسام',
    lastName: 'پورسادات',
    username: 'hesam_student',
    phone: '09123456789',
    email: 'student@demo.com',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    isActive: true,
    createdAt: '2026-02-01T12:00:00.000Z',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course_1',
    title: 'جامع آمادگی آزمون آیلتس (IELTS Masterclass)',
    slug: 'ielts-masterclass',
    description: 'کامل‌ترین دوره آمادگی آیلتس آکادمیک و جنرال با تمرکز ویژه بر تکنیک‌های Writing Task 2 و Speaking پیشرفته همراه با تحلیل تست‌های کمبریج.',
    level: 'آمادگی آیلتس',
    thumbnailUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    sessionCount: 24,
    durationHours: 48,
    price: 3800000,
    discountPercent: 15,
    finalPrice: 3230000,
    type: 'online',
    status: 'published',
    createdAt: '2026-01-10T10:00:00.000Z',
    lessons: [
      { id: 'l1', courseId: 'course_1', title: 'آشنایی با ساختار آیلتس و معیارهای نمره‌دهی', order: 1, duration: '45 دقیقه', isFree: true, description: 'معرفی باند اسکورها و سیستم ارزیابی رایتینگ و اسپیکینگ' },
      { id: 'l2', courseId: 'course_1', title: 'تکنیک‌های خواندن سریع (Skimming & Scanning)', order: 2, duration: '60 دقیقه', isFree: false, description: 'راهبردهای زمان‌بندی بخش ریدینگ' },
      { id: 'l3', courseId: 'course_1', title: 'تحلیل رایتینگ تسک ۱ (گراف و نقشه)', order: 3, duration: '75 دقیقه', isFree: false, description: 'واژگان توصیفی و گرامر مقایسه‌ای' },
    ],
  },
  {
    id: 'course_2',
    title: 'مکالمه کاربردی و روزمره انگلیسی (Real-Life English)',
    slug: 'real-life-english',
    description: 'تقویت مهارت گفتاری، اصطلاحات خیابانی و طبیعی، تلفظ صحیح امریکن و رفع استرس در مکالمه واقعی با پارتنرهای انگلیسی‌زبان.',
    level: 'متوسط (B1-B2)',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
    teacherId: 'user_teacher_2',
    teacherName: 'سارا احمدی',
    sessionCount: 18,
    durationHours: 36,
    price: 2400000,
    discountPercent: 20,
    finalPrice: 1920000,
    type: 'hybrid',
    status: 'published',
    createdAt: '2026-01-15T11:00:00.000Z',
    lessons: [
      { id: 'l4', courseId: 'course_2', title: 'اصطلاحات پرکاربرد روزمره و برقراری ارتباط اولیه', order: 1, duration: '50 دقیقه', isFree: true, description: 'احوالپرسی طبیعی، اسلنگ‌های آمریکایی' },
      { id: 'l5', courseId: 'course_2', title: 'مکالمه در فرودگاه، هتل و سفر', order: 2, duration: '55 دقیقه', isFree: false, description: 'مکالمات شبیه‌سازی شده مسافرت' },
    ],
  },
  {
    id: 'course_3',
    title: 'دوره صفر تا صد گرامر و ساختار زبان (English Grammar Mastery)',
    slug: 'grammar-mastery',
    description: 'تسلط کامل بر تمام زمان‌ها، جملات شرطی، مجهول و گرامرهای پیشرفته به روش مفهومی بدون نیاز به حفظ کردن فرمول‌ها.',
    level: 'مبتدی (A1-A2)',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    sessionCount: 20,
    durationHours: 30,
    price: 1800000,
    discountPercent: 10,
    finalPrice: 1620000,
    type: 'online',
    status: 'published',
    createdAt: '2026-01-20T14:00:00.000Z',
  },
  {
    id: 'course_4',
    title: 'انگلیسی تجاری و نامه‌نگاری اداری (Business English)',
    slug: 'business-english',
    description: 'آموزش اصول مکاتبات اداری، ایمیل‌نویسی استاندارد، مذاکرات بین‌المللی و واژگان تخصصی کسب‌وکار و تجارت بین‌الملل.',
    level: 'پیشرفته (C1-C2)',
    thumbnailUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
    teacherId: 'user_teacher_2',
    teacherName: 'سارا احمدی',
    sessionCount: 16,
    durationHours: 32,
    price: 3200000,
    discountPercent: 0,
    finalPrice: 3200000,
    type: 'inPerson',
    status: 'published',
    createdAt: '2026-02-01T09:00:00.000Z',
  },
];

export const INITIAL_CLASSES: ClassItem[] = [
  {
    id: 'class_1',
    title: 'کلاس آنلاین اسپیکینگ آیلتس (کد A-101)',
    courseId: 'course_1',
    courseTitle: 'جامع آمادگی آزمون آیلتس',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    level: 'آمادگی آیلتس',
    capacity: 12,
    enrolledCount: 9,
    startDate: '2026-09-15',
    endDate: '2026-11-20',
    weekDays: [0, 2], // شنبه و دوشنبه
    startTime: '18:00',
    endTime: '19:30',
    type: 'online',
    status: 'live',
    createdAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'class_2',
    title: 'ورکشاپ مکالمه پیشرفته انگلیسی (کد C-202)',
    courseId: 'course_2',
    courseTitle: 'مکالمه کاربردی و روزمره انگلیسی',
    teacherId: 'user_teacher_2',
    teacherName: 'سارا احمدی',
    level: 'متوسط (B1-B2)',
    capacity: 15,
    enrolledCount: 11,
    startDate: '2026-09-18',
    endDate: '2026-12-05',
    weekDays: [1, 3], // یکشنبه و سه‌شنبه
    startTime: '17:00',
    endTime: '18:30',
    type: 'online',
    status: 'scheduled',
    createdAt: '2026-08-10T10:00:00.000Z',
  },
  {
    id: 'class_3',
    title: 'کلاس حضوری بیزنس انگلیش (کد B-303)',
    courseId: 'course_4',
    courseTitle: 'انگلیسی تجاری و نامه‌نگاری اداری',
    teacherId: 'user_teacher_2',
    teacherName: 'سارا احمدی',
    level: 'پیشرفته (C1-C2)',
    capacity: 10,
    enrolledCount: 7,
    startDate: '2026-09-20',
    endDate: '2026-11-15',
    weekDays: [4], // چهارشنبه
    startTime: '16:00',
    endTime: '19:00',
    type: 'inPerson',
    status: 'scheduled',
    createdAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'class_4',
    title: 'کلاس آنلاین گرامر کاربردی ویژه مبتدیان',
    courseId: 'course_3',
    courseTitle: 'دوره صفر تا صد گرامر و ساختار زبان',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    level: 'مبتدی (A1-A2)',
    capacity: 20,
    enrolledCount: 16,
    startDate: '2026-09-10',
    endDate: '2026-10-30',
    weekDays: [0, 4], // شنبه و چهارشنبه
    startTime: '20:00',
    endTime: '21:30',
    type: 'online',
    status: 'scheduled',
    createdAt: '2026-08-05T10:00:00.000Z',
  },
  {
    id: 'class_5',
    title: 'کلاس فشرده لیسنینگ و ریدینگ آیلتس',
    courseId: 'course_1',
    courseTitle: 'جامع آمادگی آزمون آیلتس',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    level: 'آمادگی آیلتس',
    capacity: 14,
    enrolledCount: 14,
    startDate: '2026-07-01',
    endDate: '2026-08-25',
    weekDays: [5], // پنج‌شنبه
    startTime: '09:00',
    endTime: '12:00',
    type: 'online',
    status: 'finished',
    createdAt: '2026-06-15T08:00:00.000Z',
  },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'book_1',
    title: 'American English File 3 (ویرایش سوم)',
    author: 'Christina Latham-Koenig & Clive Oxenden',
    description: 'کتاب آموزش زبان پرفروش انتشارات آکسفورد ویژه سطوح متوسط، همراه با فایل‌های صوتی و ویدیوهای تعاملی.',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    price: 320000,
    discountPercent: 15,
    finalPrice: 272000,
    stock: 28,
    category: 'دوره‌های آموزشی',
    isActive: true,
    pages: 168,
    level: 'متوسط B1',
  },
  {
    id: 'book_2',
    title: 'English Grammar in Use (Raymond Murphy)',
    author: 'Raymond Murphy (Cambridge)',
    description: 'معتبرترین مرجع یادگیری گرامر انگلیسی جهان به زبان ساده، با تمرین‌های کاربردی و کلید پاسخ کامل.',
    coverUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777f?auto=format&fit=crop&w=600&q=80',
    price: 390000,
    discountPercent: 10,
    finalPrice: 351000,
    stock: 45,
    category: 'دستور زبان (Grammar)',
    isActive: true,
    pages: 390,
    level: 'تمام سطوح',
  },
  {
    id: 'book_3',
    title: 'Oxford Word Skills (Advanced)',
    author: 'Ruth Gairns & Stuart Redman',
    description: 'مجموعه تخصصی تقویت دایره لغات در بیش از ۸۰ موضوع پرکاربرد همراه با تمرین‌های استاندارد.',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    price: 310000,
    discountPercent: 20,
    finalPrice: 248000,
    stock: 14,
    category: 'واژگان و لغات',
    isActive: true,
    pages: 260,
    level: 'پیشرفته C1',
  },
  {
    id: 'book_4',
    title: 'The Official Cambridge Guide to IELTS',
    author: 'Pauline Cullen & Amanda French',
    description: 'کتاب راهنمای رسمی کمبریج برای هر دو ماژول آزمون آیلتس به همراه ۸ تست آزمایشی کامل و نکات کلیدی ممتحنین.',
    coverUrl: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&w=600&q=80',
    price: 540000,
    discountPercent: 25,
    finalPrice: 405000,
    stock: 19,
    category: 'آزمون‌های بین‌المللی',
    isActive: true,
    pages: 402,
    level: 'آیلتس',
  },
  {
    id: 'book_5',
    title: 'English Collocations in Use (Intermediate)',
    author: 'Michael McCarthy & Felicity O\'Dell',
    description: 'یادگیری کلمات همنشین (Collocations) برای صحبت کردن و نوشتن طبیعی‌تر مثل یک فرد انگلیسی‌زبان.',
    coverUrl: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
    price: 280000,
    discountPercent: 10,
    finalPrice: 252000,
    stock: 8,
    category: 'واژگان و لغات',
    isActive: true,
    pages: 190,
    level: 'متوسط B2',
  },
  {
    id: 'book_6',
    title: 'Barron\'s Essential Words for the IELTS',
    author: 'Lin Lougheed',
    description: '۶۰۰ واژه ضروری و پرتکرار آزمون آیلتس در قالب متون تخصصی، تمرین‌ها و ریدینگ‌های آزمون اصلی.',
    coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80',
    price: 260000,
    discountPercent: 15,
    finalPrice: 221000,
    stock: 32,
    category: 'آزمون‌های بین‌المللی',
    isActive: true,
    pages: 360,
    level: 'آیلتس',
  },
];

export const INITIAL_VIDEOS: RecordedVideo[] = [
  {
    id: 'video_1',
    title: 'جلسه اول: فرمول طلایی رایتینگ تسک ۲ آیلتس',
    description: 'بررسی پاراگراف‌بندی، ایده‌پردازی و اشتباهات مهلک نمره‌کاه در رایتینگ آیلتس توسط دکتر رضایی.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    courseId: 'course_1',
    courseTitle: 'جامع آمادگی آزمون آیلتس',
    duration: '45:12',
    publishedAt: '2026-08-20T10:00:00.000Z',
    isPublic: true,
  },
  {
    id: 'video_2',
    title: 'تکنیک‌های رفع لهجه و تلفظ طبیعی امریکن',
    description: 'تمرین چسباندن کلمات (Connected Speech) و ادای صحیح صداهای دشوار انگلیسی.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    teacherId: 'user_teacher_2',
    teacherName: 'سارا احمدی',
    courseId: 'course_2',
    courseTitle: 'مکالمه کاربردی و روزمره انگلیسی',
    duration: '32:40',
    publishedAt: '2026-08-25T14:00:00.000Z',
    isPublic: true,
  },
  {
    id: 'video_3',
    title: 'تفاوت زمان حال کامل و گذشته ساده با مثال‌های واقعی',
    description: 'آموزش ساختاری بدون حفظیات برای درک تفاوت Present Perfect و Past Simple.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    courseId: 'course_3',
    courseTitle: 'دوره صفر تا صد گرامر و ساختار زبان',
    duration: '28:15',
    publishedAt: '2026-09-01T11:00:00.000Z',
    isPublic: true,
  },
  {
    id: 'video_4',
    title: 'نحوه نوشتن ایمیل رسمی برای درخواست‌های بین‌المللی',
    description: 'قالب‌های استاندارد اداری، اصطلاحات مؤدبانه و نحوه پیگیری ایمیل کاری.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    teacherId: 'user_teacher_2',
    teacherName: 'سارا احمدی',
    courseId: 'course_4',
    courseTitle: 'انگلیسی تجاری و نامه‌نگاری اداری',
    duration: '40:05',
    publishedAt: '2026-09-05T16:00:00.000Z',
    isPublic: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'order_1001',
    orderNumber: 'POL-9021',
    userId: 'user_student_1',
    userName: 'حسام پورسادات',
    userEmail: 'student@demo.com',
    userPhone: '09123456789',
    items: [
      {
        itemType: 'course',
        itemId: 'course_1',
        title: 'جامع آمادگی آزمون آیلتس (IELTS Masterclass)',
        price: 3800000,
        finalPrice: 3230000,
        qty: 1,
        imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=400&q=80',
      },
      {
        itemType: 'book',
        itemId: 'book_4',
        title: 'The Official Cambridge Guide to IELTS',
        price: 540000,
        finalPrice: 405000,
        qty: 1,
        imageUrl: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&w=400&q=80',
      },
    ],
    subtotal: 4340000,
    discount: 705000,
    shippingCost: 45000,
    total: 3680000,
    paymentStatus: 'paid',
    orderStatus: 'completed',
    address: 'تهران، خیابان ولیعصر، کوچه بهار، پلاک ۴، واحد ۲',
    createdAt: '2026-09-02T14:30:00.000Z',
  },
  {
    id: 'order_1002',
    orderNumber: 'POL-9022',
    userId: 'user_student_1',
    userName: 'حسام پورسادات',
    userEmail: 'student@demo.com',
    userPhone: '09123456789',
    items: [
      {
        itemType: 'book',
        itemId: 'book_2',
        title: 'English Grammar in Use',
        price: 390000,
        finalPrice: 351000,
        qty: 1,
        imageUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777f?auto=format&fit=crop&w=400&q=80',
      },
    ],
    subtotal: 390000,
    discount: 39000,
    shippingCost: 45000,
    total: 396000,
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    address: 'تهران، ونک، خ ملاصدرا، پلاک ۸',
    createdAt: '2026-09-08T11:20:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'user_student_1',
    title: 'کلاس آنلاین در حال برگزاری است!',
    body: 'کلاس آنلاین اسپیکینگ آیلتس (کد A-101) هم‌اکنون آغاز شده است. جهت ورود کلیک نمایید.',
    type: 'live_class_started',
    isRead: false,
    link: '/live/class_1',
    createdAt: '2026-09-14T04:15:00.000Z',
  },
  {
    id: 'notif_2',
    userId: 'user_student_1',
    title: 'تغییر ساعت کلاس اسپیکینگ',
    body: 'ساعت کلاس [کلاس آنلاین اسپیکینگ آیلتس] تغییر کرده است. زمان جدید: شنبه و دوشنبه ساعت ۱۸:۰۰ الی ۱۹:۳۰',
    type: 'class_time_changed',
    isRead: true,
    link: '/dashboard/schedule',
    createdAt: '2026-09-12T09:00:00.000Z',
  },
  {
    id: 'notif_3',
    userId: 'user_student_1',
    title: 'ثبت سفارش با موفقیت انجام شد',
    body: 'سفارش شماره POL-9021 با موفقیت پرداخت و ثبت گردید.',
    type: 'payment_success',
    isRead: true,
    link: '/dashboard/orders',
    createdAt: '2026-09-02T14:31:00.000Z',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'assign_1',
    classId: 'class_1',
    classTitle: 'کلاس آنلاین اسپیکینگ آیلتس (کد A-101)',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    title: 'تمرین ضبط صوت اسپیکینگ پارت ۲ (Cue Card)',
    description: 'لطفاً یک فایل صوتی ۲ دقیقه‌ای در خصوص توصیف یک کتاب تأثیرگذار که خوانده‌اید ضبط کرده و ارسال نمایید.',
    dueDate: '2026-09-20',
    maxScore: 20,
    submissionsCount: 7,
    createdAt: '2026-09-10T12:00:00.000Z',
  },
  {
    id: 'assign_2',
    classId: 'class_1',
    classTitle: 'کلاس آنلاین اسپیکینگ آیلتس (کد A-101)',
    teacherId: 'user_teacher_1',
    teacherName: 'دکتر محمدرضا رضایی',
    title: 'رایتینگ تسک ۲: هوش مصنوعی و آموزش',
    description: 'یک مقاله ۲۵۰ کلمه‌ای با ساختار استاندارد ۴ پاراگرافی در پاسخ به سوال مشخص شده بنویسید.',
    dueDate: '2026-09-25',
    maxScore: 100,
    submissionsCount: 4,
    createdAt: '2026-09-12T14:00:00.000Z',
  },
];
